name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # uv環境のセットアップ
      - name: Install uv
        run: |
          pip install pipx
          pipx install uv
          uv sync

      # 型チェック
      - name: Run mypy
        run: uv run mypy app/

      # テストの実行
      - name: Run pytest
        run: uv run pytest tests/
