name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set environment variables
        env:
          GCP_SA_CREDENTIAL: ${{ secrets.GCP_SA_CREDENTIAL }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          echo "Environment variable set successfully."

      - name: Install uv
        run: |
          pip install pipx
          pipx install uv
          uv sync

      # 型チェック
      - name: Run mypy
        run: uv run mypy app/

      # テストの実行
      - name: Run pytest
        run: uv run pytest tests/
