name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.CICD_GCP_SA_CREDENTIAL }}"

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GCP_SA_CREDENTIAL: ${{ secrets.GCP_SA_CREDENTIAL }}
        run: |
          IMAGE="asia-northeast1-docker.pkg.dev/$PROJECT_ID/recipe/recipe-app:dev"
          docker build \
            --no-cache=true \
            --platform linux/x86_64 \
            --build-arg GCP_SA_CREDENTIAL="$GCP_SA_CREDENTIAL" \
            -f Dockerfile . \
            -t "$IMAGE"
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud run deploy recipe-service-app \
            --project $PROJECT_ID \
            --image "asia-northeast1-docker.pkg.dev/$PROJECT_ID/recipe/recipe-app:dev" \
            --region asia-northeast1 \
            --platform managed \
            --allow-unauthenticated
